// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaInZ5Z68rvMGC1hTMiA47lcAVGKejnE',
    appId: '1:721561322441:web:6db9a6277e6b273e4fde18',
    messagingSenderId: '721561322441',
    projectId: 'zphos-6d37f',
    authDomain: 'zphos-6d37f.firebaseapp.com',
    storageBucket: 'zphos-6d37f.appspot.com',
    measurementId: 'G-PV6WGWY1LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2QlFrPofrU_ky8NjrovDQYHIrEU5eu0',
    appId: '1:721561322441:android:6fbc86582a66b9ab4fde18',
    messagingSenderId: '721561322441',
    projectId: 'zphos-6d37f',
    storageBucket: 'zphos-6d37f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ff3pUu3_n3SuynHM4EQLclqXNVGl2ss',
    appId: '1:721561322441:ios:c79d2723a59ecc9d4fde18',
    messagingSenderId: '721561322441',
    projectId: 'zphos-6d37f',
    storageBucket: 'zphos-6d37f.appspot.com',
    iosClientId:
        '721561322441-lr1dod2nh9605cr9dfv7am9lt0tq31rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.zphos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ff3pUu3_n3SuynHM4EQLclqXNVGl2ss',
    appId: '1:721561322441:ios:c79d2723a59ecc9d4fde18',
    messagingSenderId: '721561322441',
    projectId: 'zphos-6d37f',
    storageBucket: 'zphos-6d37f.appspot.com',
    iosClientId:
        '721561322441-lr1dod2nh9605cr9dfv7am9lt0tq31rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.zphos',
  );
}
